import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify AI - created by Yogeshkumar S",
  description: "Generated by SPOTIFY AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative bg-black text-white overflow-x-hidden">

  {/* Global AI Glow */}
  <div
    className="
      pointer-events-none fixed inset-0 z-0
      bg-[radial-gradient(circle_at_top,_rgba(34,197,94,0.18),transparent_60%)]
    "
  />

  {/* Page Content */}
  <div className="relative z-10">
    {children}
  </div>

</body>

    </html>
  );
}
